# This file contains all available configuration options
# with their default values.

# options for analysis running
run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 3m

linters:
  disable-all: true
  enable:
    - megacheck
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - golint
    - stylecheck
    - gosec
    - interfacer
    - unconvert
    - dupl
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - maligned
    - depguard
    - misspell
    - unparam
    - nakedret
    - prealloc
    - scopelint
    - gocritic
    - gochecknoinits
    - gochecknoglobals

